- hosts: <<hostname>>
  become: yes
  become_user: root
  become_method: sudo

  vars_prompt:
  - name: user_name
    prompt: Enter the user name for password reset
    private: no
  - name: pass
    prompt: Enter the password

  tasks:

  - name: Gather facts from new server
    setup:
      filter: ansible_facts.getent_passwd

  - name: Change {{ user_name }}  password
    user:
      name: {{ user_name }}
      password: {{ pass|password_hash('sha512') }}
      update_password: always
    when: item in ansible_facts.getent_passwd